### ISSUE TITLE
Some GUI suggestions

### ISSUE THREAD

**Issue by peter-shen-dev** [st17180/PySource#7]
1. 'processes' command prints '[]' at the end
2. 'save' command isn't shown in help
3. 'processes' display would be a bit easier to parse if the columns were aligned

**Comment by st17180** [comment]
addressed here https://github.com/st17180/PySource/commit/b3041cf9b31f20bad51d2520666d3547896e2770
![image](https://user-images.githubusercontent.com/70176066/120726656-b4f32a80-c52c-11eb-8a1b-f60af5b79113.png)
and
![image](https://user-images.githubusercontent.com/70176066/120726671-c0465600-c52c-11eb-920d-105415d2aab2.png)

Thanks for the feedback!
