### ISSUE TITLE
Feedback - William

### ISSUE THREAD

**Issue by SkinFart** [st17180/PySource#8]
windows processes/save needs elevated prvilages
label CLI output some more
windows does only 1 drive

**Comment by st17180** [comment]
added comments for windows limitations in the read-me, elevating privileges within the program seems like too big of a security flaw.

windows should run the drive check on whatever drive the system is installed on.

**Comment by st17180** [comment]
alright, addressed with https://github.com/st17180/PySource/commit/71cadfba98cf660751c95378d45fb47a7c961b02 for documentation on windows there

some more CLI comments were added as well here https://github.com/st17180/PySource/commit/9e2cb2bab0a6f650d3f37ee654aa702b8e1c8c63
